[project]
name = "python-notebook-examples-in-tensorflow-20250920"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.0.1",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "tensorflow>=2.20.0",
]
